# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Samuel Sears
# Description of the Site
description: Data Science Portfolio
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Samuel Sears, Data Science, Portfolio
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images3.alphacoders.com/536/53625.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ssears219@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: samuel-sears-86b635102
github_username:  ssears219
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username:
spotify_username: 

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Samuel Sears
# URL for the Image of the Author
author-image: https://media-exp1.licdn.com/dms/image/C4E03AQHJF2zyE95WOg/profile-displayphoto-shrink_200_200/0/1630445305065?e=1654128000&v=beta&t=-gXKbvkbn8TFcIhb6Pa1f-AC7BTp7YGwO7AS4qceuO8
# 60 Words About the Author
author-about: Innovative and Resourceful Business Analyst with extensive Data Science knowledge. Experience working in a fast-paced, Agile environment. Strong ability to analyze data and communicate findings to colleagues and partners. Adept at implementing machine learning solutions within team processes.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ssears219

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
